---
title: "Area 8 Chum Data Prep"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r setup, echo=FALSE,message=FALSE,warning=FALSE}
#load libraries
knitr::opts_chunk$set(echo = TRUE, fig.pos = "!h")

library(data.table)
library(tidyverse)
library(dplyr)
library(zoo)
library(ggplot2)
options(scipen=10000)

```


```{r functions, echo=FALSE,message=FALSE,warning=FALSE}
#function to extract data and group it

getridofggplotlinesbetweenpoints<-function(data,colstokeep,yearcolumnname) {
  d2<-data%>%select(year=yearcolumnname,colstokeep)
  idx <- c(1, diff(d2$year))
  i2 <- c(1,which(idx != 1), nrow(d2)+1)
  d2$grp <- rep(1:length(diff(i2)), diff(i2))
  d2
}
```



```{r load prep data, echo=FALSE,message=FALSE,warning=FALSE}
#load escapement data and remove 0's

escdata<-fread("data/all nuseds with enhancement rankings.csv")%>%
  select(-V1)

escdata$escapement[escdata$escapement==0]<-NA

escdata.raw<-escdata%>%filter(SPP=="CM"&Area==8)

write.csv(escdata,"data/area 8 chum escapement data all.csv")

saveRDS(escdata, "RDS/a08cm_escdata.rds")

#bubbleplot of escapements for whole area
ggplot(escdata.raw,aes(x=Year,y=SYS_NM,color=Enhancement_Rank,size=escapement))+
  geom_point(alpha=.5)+
  scale_colour_manual(breaks=c("NONE","LOW","MOD","HIGH"),
                      values=c("grey50","steelblue","darkred","seagreen"))+
  labs(y="Escapement",color="Enhancement",x="Year",size="Escapement")+
  theme_bw()+
  theme(legend.position="bottom")

#unique(escdata.raw$SYS_NM)
ggsave("figures/area 8 chum escapement all streams.png",dpi=600,height=8,width=7)
```


```{r filter escapement data, echo=FALSE,message=FALSE,warning=FALSE}
# Add filter by year
fy=1980
n.pre=(fy-1950)/2
n.post=(2018-fy)/2

included.stream.list<-escdata.raw%>%
  mutate(prepost=case_when(Year<1980~"Pre",
                           Year>=1980~"Post"))%>%
  group_by(SYS_NM,prepost)%>%
  summarise(notnas=sum(!is.na(escapement)))%>%
  pivot_wider(names_from="prepost",values_from="notnas")%>%
  filter(Post>n.post&Pre>n.pre)

write.csv(included.stream.list,"data/area 8 chum filtered stream list.csv")

#add escapement metrics and pre/post field
escdata.filtered<-escdata.raw%>%filter(SYS_NM%in%included.stream.list$SYS_NM)%>%
  group_by(SYS_NM)%>%
  arrange(SYS_NM,Year)%>%
  mutate(esc.log=log(escapement),
         z=(esc.log-mean(esc.log,na.rm=TRUE))/sd(esc.log,na.rm=TRUE),
         m.ave=rollapply(esc.log,4,mean,align='right',fill=NA),
         esc.stand=esc.log/mean(esc.log,na.rm=TRUE),
         prepost=case_when(Year<1980~"Pre",
                           Year>=1980~"Post"))

saveRDS(escdata.filtered, "RDS/a08cm_escdata_filtered.rds")

write.csv(escdata.filtered,"data/area 8 chum escapement data filtered with metrics.csv")

ggplot(escdata.filtered,aes(x=Year,y=escapement,color=Enhancement_Rank))+
  geom_point()+geom_line()+theme_bw()+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")+
  labs(y="Escapement",color="Enhancement Level",title="Area 6 Escapement (filtered streams)")+
  theme(legend.position="bottom")

ggsave("figures/area 8 chum escapement filtered streams.png",dpi=600,height=8,width=7)

```


```{r releases for area 8}
releases.raw<-fread("data/AllSEPReleases_2021-01-21 with otoliths revised.csv")

allreleases <- releases.raw %>%
  select(SPECIES_NAME, STOCK_NAME, FACILITY_NAME, RELEASE_SITE_NAME,
         RELEASE_STAGE_NAME, TotalRelease, RELEASE_YEAR, REL_CU_NAME,
         REL_CU_INDEX) %>%
  group_by(SPECIES_NAME,REL_CU_NAME,REL_CU_INDEX,STOCK_NAME,RELEASE_SITE_NAME,
           FACILITY_NAME,RELEASE_STAGE_NAME,RELEASE_YEAR) %>%
  summarise(releases=sum(as.numeric(TotalRelease)),n=n()) %>% 
  ungroup()

allcunames<-allreleases%>%filter(SPECIES_NAME==species)%>%distinct(REL_CU_NAME)
allreleasesites<-allreleases%>%filter(SPECIES_NAME==species&REL_CU_NAME=="")%>%distinct(RELEASE_SITE_NAME,STOCK_NAME)

species="Chum"
rel.cu.name=c("BELLA COOLA RIVER-LATE","BELLA COOLA-DEAN RIVERS","SPILLER-FITZ HUGH-BURKE")

releases <- allreleases %>% 
  data.frame() %>% 
  filter(SPECIES_NAME==species&REL_CU_NAME%in%rel.cu.name)%>%
  mutate("site-stock"=paste0(RELEASE_SITE_NAME,":",STOCK_NAME))%>%
  filter(!is.na(releases))%>%
  arrange(`site-stock`,RELEASE_STAGE_NAME,RELEASE_YEAR)

extra.releasesites<-c("Bella Coola Est","Bella Coola R Low","Bentinck Arm N","Hagensborg Sl","Nooklikonnick Cr")

extras<-allreleases%>%data.frame()%>%
  filter(REL_CU_NAME==""&RELEASE_SITE_NAME%in%extra.releasesites)%>%
  mutate("site-stock"=paste0(RELEASE_SITE_NAME,":",STOCK_NAME))%>%
  filter(!is.na(releases))%>%
  arrange(`site-stock`,RELEASE_STAGE_NAME,RELEASE_YEAR)

releases<-rbind(releases,extras)

idx <- c(1, diff(releases$RELEASE_YEAR))
i2 <- c(1,which(idx != 1), nrow(releases)+1)
releases$grp <- rep(1:length(diff(i2)), diff(i2))

saveRDS(releases, "RDS/a08cm_releases.rds")

#plot all releases in area to determine which systems specifically to included
ggplot(releases,aes(x=RELEASE_YEAR,y=releases,color=RELEASE_STAGE_NAME,group=grp))+
  geom_line()+geom_point()+
  scale_color_brewer(palette="Set1")+
  facet_wrap(~`site-stock`,ncol=4)+
  theme_bw()+
  labs(x="Release Year",y="Releases",color="Release Stage",
       title=paste0(species,": ",paste0(rel.cu.name,collapse=" ")),subtitle="Release site:Origin stock")+
  theme(legend.position = "bottom",
        plot.title=element_text(size=8),strip.text=element_text(size=8))

#ggsave("figures/releases chum area 8 by CU.png",dpi=600,height=8,width=7)

#write.csv(releases,"data/releases area 8 chum all.csv")

```


```{r total releases for area 8 terminal not including mcloughlin bay}
#total releases for BC and MB
releases.BCMB<-releases %>% 
  filter(RELEASE_SITE_NAME%in%c("Fish Cr+Airport Ch","Saloompt R","Snootli Cr","Thorsen Cr/CCST","McLoughlin Bay"))

totalrel.BCMB <- releases.BCMB %>% 
  group_by(RELEASE_YEAR)%>%
  summarise(totreleases=sum(releases))%>%
  mutate(group="BC/MB")

#total releases for just MB
releases.MB<-releases %>% 
  filter(RELEASE_SITE_NAME%in%c("McLoughlin Bay"))

totalrel.MB <- releases.MB %>% 
  group_by(RELEASE_YEAR)%>%
  summarise(totreleases=sum(releases))%>%
  mutate(group="MB")

saveRDS(totalrel.MB, "RDS/totrelMB.rds")

#total releases for just BC
releases.BC<-releases %>% 
  filter(RELEASE_SITE_NAME%in%c("Fish Cr+Airport Ch","Saloompt R","Snootli Cr","Thorsen Cr/CCST"))

totalrel.BC <- releases.BC %>% 
  group_by(RELEASE_YEAR)%>%
  summarise(totreleases=sum(releases))%>%
  mutate(group="BC")

saveRDS(totalrel.BC, "RDS/totrelBC.rds")

totrel<-rbind(totalrel.BC,totalrel.BCMB,totalrel.MB)

totrelwide<-totrel%>%pivot_wider(names_from="group",values_from="totreleases")

write.csv(totrelwide,"data/releases area 8 chum total terminal releases by group.csv")
```


```{r plot total releases}
ggplot(totrel,aes(x=RELEASE_YEAR,y=totreleases,color=group))+
  geom_point()+geom_line()+
  theme_bw()+
  labs(x="Release Year",y="Total Releases",title="Area 8 Chum total terminal releases (excludes Mcloughlin Bay)")

#ggsave("figures/releases chum area 8 total terminal.png",dpi=600,height=6,width=6)

#write.csv(totrel,"~/R/PSF hatchery review/analysis/spatial/outputs/Area 25 chum releases totals.csv")
```

``` {r prep rps data}
escdata<-fread("data/area 8 chum escapement data filtered with metrics.csv")

age<-fread("data/age and ERs NC CC PSE.csv")

ageERs<-age%>%filter(SpeciesId=="CM",CU_Name=="Bella Coola-Dean Rivers, BELLA COOLA RIVER-LATE")%>%select(Year=BroodYear,`Total ER`,p3=Age3,p4=Age4,p5=Age5)

rps<-merge(escdata,ageERs,by="Year")%>%
  mutate(TR=escapement/(1-`Total ER`))%>%
  mutate(age3=TR*p3,age4=TR*p4,age5=TR*p5)%>%
  arrange(SYS_NM,Year)%>%
  mutate(r3=shift(age3,n=-3,type="lag"),r4=shift(age4,n=-4,type="lag"),
         r5=shift(age5,n=-5,type="lag"))%>%
  rowwise()%>%
  mutate(recruits=sum(dplyr::c_across(r3:r5),na.rm=TRUE))%>%
  mutate(rps=recruits/escapement,
         rps=replace(rps,rps==0,NA),
         logrps=log(rps))

rps.clean<-rps%>%select(Year,SYS_NM,prepost,escapement,r3,r4,r5,recruits,rps,logrps)%>%
  mutate(rps=replace(rps,rps>100,NA))%>%
  mutate(exclude=ifelse(is.na(r3)|is.na(r4)|is.na(r5)|rps>50,"Y","N"))%>%
  mutate(rpsclean=case_when(exclude=="N"~rps),
         logrpsclean=case_when(exclude=="N"~logrps))

saveRDS(rps.clean, "RDS/a08cm_rpsclean.rds")

write.csv(rps,"data/area 8 chum with rps raw and clean.csv")

```

```{r}
#total return plot
ggplot(rps.clean,aes(x=Year,y=escapement))+
  geom_line()+geom_point()+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")

#rps plots
ggplot(rps.clean,aes(x=Year,y=rps))+
  geom_line()+geom_point()+
  geom_smooth(method='lm',se=TRUE)+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")+
  theme_bw()+
  geom_hline(yintercept=1)

ggsave("figures/releases chum area 8 total terminal.png",dpi=600,height=6,width=6)

#log rps plots
names(rps.clean)

logrps<-rps.clean%>%select(Year,prepost,logrpsclean,SYS_NM)%>%arrange(SYS_NM,prepost,Year)

idx <- c(1, diff(logrps$Year))
i2 <- c(1,which(idx != 1), nrow(logrps)+1)
logrps$grp <- rep(1:length(diff(i2)), diff(i2))

ggplot(logrps,aes(x=Year,y=logrpsclean,color=prepost,group=grp))+
  geom_line(alpha=.5)+geom_point(alpha=.5)+
  scale_color_brewer(palette="Set1")+
  geom_smooth(method='lm',se=TRUE)+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")+
  theme_bw()+
  geom_vline(xintercept=fy,color="seagreen")+
  geom_hline(yintercept=0,linetype="dashed")+
  labs(x="Brood Year",y="log(Recruits per spawner)",color="Period",title="Area 8 Chum")+
  theme(legend.position="bottom")

ggsave("figures/area 8 chum log rps pre vs post.png",dpi=600,height=8,width=7)

ggplot(logrps,aes( y = SYS_NM, x = logrpsclean, fill = prepost))+
  geom_boxplot(notch=F)+
  scale_fill_brewer(palette="Set1")+
  geom_vline(xintercept=0)+
  theme_bw()+
  labs(y="System Name",x="log(Recruits per spawner)",title="Area 8 Chum")+
  theme(legend.position="bottom")

ggsave("figures/area 8 chum log rps pre vs post boxplot.png",dpi=600,height=8,width=7)

```

```{r, Import and merge stream distances by system and (sub)inlets}
mcloughlin <- read_csv("data/area 8 chum stream distance from mcloughlin.csv")
bellacoola <- read_csv("data/area 8 chum stream distance from bella coola.csv")

names(mcloughlin) <- c("SYS_NM", "dist_km_mcl")
names(bellacoola) <- c("SYS_NM", "dist_km_bel")

rps.clean <- read_csv("data/area 8 chum with rps raw and clean.csv")
inlets <- read_csv("data/area 8 chum filtered stream list with inlets and distance.csv")

rps.clean <- merge(mcloughlin, rps.clean, by = "SYS_NM")
rps.clean <- merge(bellacoola, rps.clean, by = "SYS_NM")
rps.clean <- merge(inlets, rps.clean, by = "SYS_NM")

saveRDS(rps.clean, "RDS/a08cm_rpsclean.rds")
```

```{r, Prep weighted averages of distances by releases}

totrelBC <- readRDS("RDS/totrelBC.rds")
totrelMB <- readRDS("RDS/totrelMB.rds")

colnames(totrelBC) <- c("Year", "releases_bel", "group")
totrelBC <- totrelBC[,1:2]

colnames(totrelMB) <- c("Year", "releases_mcl", "group")
totrelMB <- totrelMB[,1:2]

rps.clean <- merge(totrelBC, rps.clean, by = "Year", all = TRUE)
rps.clean <- merge(totrelMB, rps.clean, by = "Year", all = TRUE)

weightstable_bel <- rps.clean %>%
  drop_na() %>%
  group_by(SYS_NM) %>%
  summarize(weighted.mean(dist_km_bel, releases_bel))
colnames(weightstable_bel) <- c("SYS_NM", "wt_dist_bel")

weightstable_mcl <- rps.clean %>%
  drop_na() %>%
  group_by(SYS_NM) %>%
  summarize(weighted.mean(dist_km_mcl, releases_mcl))
colnames(weightstable_mcl) <- c("SYS_NM", "wt_dist_mcl")

rps.clean <- merge(weightstable_bel, rps.clean, by = "SYS_NM", all = TRUE)
rps.clean <- merge(weightstable_mcl, rps.clean, by = "SYS_NM", all = TRUE)

saveRDS(rps.clean, "RDS/a08cm_rpsclean.rds")
```
