---
title: "A25 CM SR RPS Workup"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}

library(tidyverse)
library(data.table)
library(dplyr)
library(corrplot)
nameslookup <- readRDS("nameslookup.rds")

escdata <- read_csv("all nuseds with enhancement rankings.csv")%>%
  select(-V1)

escdata$escapement[escdata$escapement==0]<-NA

species="CM"
area=25
rel.site.names<-c("Canton Cr","Canton Est","Conuma Est","Conuma R Up","Conuma R",
             "Deserted R/NWVI","Moutcha Bay","Sucwoa R","Tlupana R","Zeballos R")
fy=1980

esc.data<-escdata%>%filter(SPP==species&Area==area)

#apply filter - in this case need n counts out of all years
fy=1980
n.pre=(fy-1953)/2
n.post=(2018-fy)/2

included.stream.list<-esc.data%>%
  mutate(prepost=case_when(Year<1980~"Pre",
                           Year>=1980~"Post"))%>%
  group_by(SYS_NM,prepost)%>%
  summarise(notnas=sum(!is.na(escapement)))%>%
  pivot_wider(names_from="prepost",values_from="notnas")%>%
  filter(Post>n.post&Pre>n.pre)

included.stream.list

df<-esc.data%>%filter(SYS_NM%in%included.stream.list$SYS_NM)%>%
  group_by(SYS_NM)%>%
  arrange(SYS_NM,Year)%>%
  mutate(esc.log=log(escapement),
         z=(esc.log-mean(esc.log,na.rm=TRUE))/sd(esc.log,na.rm=TRUE),
         m.ave=rollapply(esc.log,4,mean,align='right',fill=NA),
         esc.stand=esc.log/mean(esc.log,na.rm=TRUE),
         prepost=case_when(Year<1980~"Pre",
                           Year>=1980~"Post"))

age<-read.delim("SCVI_age_2019-04-13.txt")

swvi.ageers<-age%>%filter(CU_Name=="Southwest & West  Vancouver Island")%>%
  select(Year=BroodYear,Total.ER,p3=Age3,p4=Age4,p5=Age5)

df2<-merge(df,swvi.ageers,by="Year")%>%
  mutate(TR=escapement/(1-Total.ER))%>%
  mutate(age3=TR*p3,age4=TR*p4,age5=TR*p5)%>%
  mutate(r3=shift(age3,n=-3,type="lag"),r4=shift(age4,n=-4,type="lag"),
         r5=shift(age5,n=-5,type="lag"))%>%
  rowwise()%>%
  mutate(recruits=sum(c_across(r3:r5),na.rm=TRUE))%>%
  mutate(rps=recruits/escapement,
         rps=replace(rps,rps==0,NA),
         logrps=log(rps))

saveRDS(df2, file = "RPS.rds") 

#total return plot
ggplot(df2, aes(x=Year,y=TR)) +
  geom_line()+
  geom_point()+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")

#rps plots
ggplot(df2,aes(x=Year,y=rps))+
  geom_line()+geom_point()+
  geom_smooth(method='lm',se=TRUE)+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")+
  theme_bw()+
  geom_hline(yintercept=1)

#log rps plots
ggplot(df2,aes(x=Year,y=logrps))+
  geom_line()+geom_point()+
  geom_smooth(method='lm',se=TRUE)+
  facet_wrap(~SYS_NM,ncol=3,scale="free_y")+
  theme_bw()+
  geom_hline(yintercept=0)


  
```

```{r, Tanglegrams for RPS pre- and post-1980 and compared to z-score}

# Corrplots

cor.data.rps <-df2 %>%
  select(SYS_NM,Year,rps) %>%
  pivot_wider(names_from="Year",values_from="rps") %>%
  data.frame()

cor.data.rps.pre<-cor.data.rps[,1:31]
rownames(cor.data.rps.pre)<-cor.data.rps.pre$SYS_NM
cor.data.rps.pre<-cor.data.rps.pre%>%select(-SYS_NM)
cor.rps.pre<-cor(t(cor.data.rps.pre),use="pairwise.complete.obs")

cor.data.rps.post<-cor.data.rps[,c(1,32:69)]
rownames(cor.data.rps.post)<-cor.data.rps.post$SYS_NM
cor.data.rps.post<-cor.data.rps.post%>%select(-SYS_NM)
cor.rps.post<-cor(t(cor.data.rps.post),use="pairwise.complete.obs")

par(mfrow=c(2,1))
corrplot(cor.rps.pre, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Recruits per spawner (Pre-1980)", cex.main = .7, mar=c(0,0,1,0))
corrplot(cor.rps.post, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Recruits per spawner (Post-1980)", sub = "Z-scores", cex.main = .7, mar=c(0,0,1,0))

# Tanglegrams

# Pre-1980
dist.cor.rps.pre <- dist(cor.rps.pre)
clust.dist.cor.rps.pre <- hclust(dist.cor.rps.pre)
tanglelabs.rps.pre <- as.data.frame(clust.dist.cor.rps.pre[["labels"]])
colnames(tanglelabs.rps.pre) <- "SYS_NM"
tanglelabs.rps.pre <- merge(tanglelabs.rps.pre, nameslookup, on = "SYS_NM")
clust.dist.cor.rps.pre[["labels"]] <- tanglelabs.rps.pre$shortnames
dendrps.pre <- as.dendrogram(clust.dist.cor.rps.pre)

# Post-1980
dist.cor.rps.post <- dist(cor.rps.post)
clust.dist.cor.rps.post <- hclust(dist.cor.rps.post)
tanglelabs.rps.post <- as.data.frame(clust.dist.cor.rps.post[["labels"]])
colnames(tanglelabs.rps.post) <- "SYS_NM"
tanglelabs.rps.post <- merge(tanglelabs.rps.post, nameslookup, on = "SYS_NM")
clust.dist.cor.rps.post[["labels"]] <- tanglelabs.rps.post$shortnames
dendrps.post <- as.dendrogram(clust.dist.cor.rps.post)

# Tanglegram

cor.data.rps <-df2 %>%
  select(SYS_NM,Year,rps) %>%
  pivot_wider(names_from="Year",values_from="rps") %>%
  data.frame()



tangle.rps <- dendlist(dendrps.pre, dendrps.post)
tanglegram(tangle.rps, lab.cex = .8, margin_inner = 3, main = "Recruits per spawner", main_left = "Pre-1980",
           main_right = "Post-1980", cex_main = 1, highlight_distinct_edges = FALSE,
           lwd = 2, edge.lwd = 1)

# Compare with z-scores

rownames(cor.data.rps)<-cor.data.rps$SYS_NM
cor.data.rps<-cor.data.rps%>%select(-SYS_NM)
cor.rps<-cor(t(cor.data.rps),use="pairwise.complete.obs")

dist.cor.rps<- dist(cor.rps)
clust.dist.cor.rps <- hclust(dist.cor.rps)

dendclust.rps <- dendro_data(clust.dist.cor.rps)
rpslabs <- as.data.frame(dendclust.rps[["labels"]][["label"]])
rpslabs$order <- 1:length(rpslabs[,1])
colnames(rpslabs) <- c("SYS_NM", "order")
rpslabs <- merge(streaminlet, rpslabs, by = "SYS_NM")
rpslabs <- merge(inlets, rpslabs, by = "inlet")
rpslabs <- rpslabs %>%
  arrange(order)
rpslabcolours <- rpslabs$colour
rpslabnames <- rpslabs$inlet.y

dendrps <- as.dendrogram(clust.dist.cor.rps)
dendrps %>%
  set("labels_colors", zlabcolours) %>%
  set("labels_cex", 0.65) %>%
  set("labels", nameslookup$shortnames) %>%
  set("leaves_pch", 19) %>%
  set("leaves_col", nameslookup$erank) %>%
  plot(main = "Recruits per spawner", horiz = TRUE)

tangle_z_rps <- dendlist(dendrps, dendz)

tanglegram(tangle_z_rps, lab.cex = .8, margin_inner = 3, main_left = "Recruits per spawner",
           main_right = "Z-score", cex_main = 1, highlight_distinct_edges = FALSE,
           lwd = 2, edge.lwd = 1)


```