---
title: "Spatial Analysis Figures"
author: "Coastland"
date: "22/10/2021"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE,message=FALSE,warning=FALSE}
#load libraries
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(tidyverse)
library(corrplot)
library(ggpubr)
library(zoo)
library(ggdendro)
library(cowplot)


options(scipen=10000)

```


```{r functions, echo=FALSE,message=FALSE,warning=FALSE}
#function to extract data and group it

getridofggplotlinesbetweenpoints<-function(data,colstokeep,yearcolumnname) {
  d2<-data%>%select(year=yearcolumnname,colstokeep)
  idx <- c(1, diff(d2$year))
  i2 <- c(1,which(idx != 1), nrow(d2)+1)
  d2$grp <- rep(1:length(diff(i2)), diff(i2))
  d2
}
```

```{r load prep data, echo=FALSE,message=FALSE,warning=FALSE}
#load escapement data and remove 0's

escdata<-fread("esc-WCVI-with-enhancement-rankings.csv")%>%
  select(-V1)

escdata$escapement[escdata$escapement==0]<-NA

```

```{r add analyses,echo=FALSE,warning=FALSE,message=FALSE}
#filter species and area
species="CM"
area=25
esc.data<-escdata%>%filter(SPP==species&Area==area)

#apply filter - in this case need n counts out of all years
n=(2018-1953)/2

included.stream.list<-esc.data%>%
  group_by(SYS_NM)%>%
  summarise(notnas=sum(!is.na(escapement)))%>%
  filter(notnas>n)

#add escapement metrics and pre/post field
df<-esc.data%>%filter(SYS_NM%in%included.stream.list$SYS_NM)%>%
  group_by(SYS_NM)%>%
  arrange(SYS_NM,Year)%>%
  mutate(esc.log=log(escapement),
         z=(esc.log-mean(esc.log,na.rm=TRUE))/sd(esc.log,na.rm=TRUE),
         m.ave=rollapply(esc.log,4,mean,align='right',fill=NA),
         esc.stand=esc.log/mean(esc.log,na.rm=TRUE),
         prepost=case_when(Year<1980~"Pre",
                           Year>=1980~"Post"))
  
```


```{r correlations for all metrics,echo=FALSE,warning=FALSE,message=FALSE}
#prep data for correlations

# Merge stream inlet table into df

streaminlet <- read_csv("CM A25 filtered stream list_with inlets.csv")

df <- df %>%
  inner_join(streaminlet, df, by = "SYS_NM")

# Factor out inlet and create df of inlet colours

df$inlet <- as.factor(df$inlet)
inlets <- as.data.frame(levels(df$inlet))
inlets$colour <- c("red", "blue", "darkgreen")
colnames(inlets) <- c("inlet", "colour")


# Correlation analysis by z-score

cor.data.z<-df%>%select(SYS_NM,Year,z)%>%pivot_wider(names_from="Year",values_from="z")%>%data.frame()

rownames(cor.data.z)<-cor.data.z$SYS_NM

cor.data.z<-cor.data.z%>%select(-SYS_NM)

cor.z<-cor(t(cor.data.z),use="pairwise.complete.obs")

# Dendrogram, factored by inlet, by z-score

dist.cor.z<- dist(cor.z)
clust.dist.cor.z <- hclust(dist.cor.z)

dendclust.z <- dendro_data(clust.dist.cor.z)
zlabs <- as.data.frame(dendclust.z[["labels"]][["label"]])
zlabs$order <- 1:length(zlabs[,1])
colnames(zlabs) <- c("SYS_NM", "order")
zlabs <- merge(streaminlet, zlabs, by = "SYS_NM")
zlabs <- zlabs %>%
  arrange(order)
inletlist <- as.factor(zlabs$inlet)
  
dendclust.z[["labels"]][["inlet"]] <- inletlist

xlenz <- .95 * length(zlabs$SYS_NM)
ylenz <- .95 * (max(dendclust.z[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.z, rotate = TRUE) +
  labs(title = "Z-scores") +
  theme(axis.text.y = element_text(colour = dendclust.z[["labels"]][["inlet"]])) +
  annotate("text", x = xlenz, y = ylenz, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlenz-1, y = ylenz, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlenz-2, y = ylenz, colour = "99FF33", label = "Tahsis inlet") 

# Correlation analysis by log escapement

cor.data.e<-df%>%select(SYS_NM,Year,esc.log)%>%pivot_wider(names_from="Year",values_from="esc.log")%>%data.frame()

rownames(cor.data.e)<-cor.data.e$SYS_NM

cor.data.e<-cor.data.e%>%select(-SYS_NM)

cor.e<-cor(t(cor.data.e),use="pairwise.complete.obs")

# Dendrogram, factored by inlet, by log escapement

dist.cor.e<- dist(cor.e)
clust.dist.cor.e <- hclust(dist.cor.e)

dendclust.e <- dendro_data(clust.dist.cor.e)
elabs <- as.data.frame(dendclust.e[["labels"]][["label"]])
elabs$order <- 1:length(elabs[,1])
colnames(elabs) <- c("SYS_NM", "order")
elabs <- merge(streaminlet, elabs, by = "SYS_NM")
elabs <- elabs %>%
  arrange(order)
inletlist <- as.factor(elabs$inlet)
  
dendclust.e[["labels"]][["inlet"]] <- inletlist

xlene <- .95 * length(elabs$SYS_NM)
ylene <- .95 * (max(dendclust.e[["segments"]][["y"]]))

ggdendrogram(dendclust.e, rotate = TRUE) +
  labs(title = "Log escapement") +
  theme(axis.text.y = element_text(colour = dendclust.e[["labels"]][["inlet"]])) +
  annotate("text", x = xlene, y = ylene, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlene-1, y = ylene, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlene-2, y = ylene, colour = "99FF33", label = "Tahsis inlet")



# Correlation analysis by standardized escapement
cor.data.s<-df%>%select(SYS_NM,Year,esc.stand)%>%pivot_wider(names_from="Year",values_from="esc.stand")%>%data.frame()

rownames(cor.data.s)<-cor.data.s$SYS_NM

cor.data.s<-cor.data.s%>%select(-SYS_NM)

cor.s<-cor(t(cor.data.s),use="pairwise.complete.obs")

# Dendrogram, factored by inlet, by standardized escapement

dist.cor.s<- dist(cor.s)
clust.dist.cor.s <- hclust(dist.cor.s)

dendclust.s <- dendro_data(clust.dist.cor.s)
slabs <- as.data.frame(dendclust.s[["labels"]][["label"]])
slabs$order <- 1:length(slabs[,1])
colnames(slabs) <- c("SYS_NM", "order")
slabs <- merge(streaminlet, slabs, by = "SYS_NM")
slabs <- slabs %>%
  arrange(order)
inletlist <- as.factor(slabs$inlet)
  
dendclust.s[["labels"]][["inlet"]] <- inletlist

xlens <- .95 * length(slabs$SYS_NM)
ylens <- .95 * (max(dendclust.s[["segments"]][["y"]]))

ggdendrogram(dendclust.s, rotate = TRUE) +
  labs(title = "Standardized escapement") +
  theme(axis.text.y = element_text(colour = dendclust.s[["labels"]][["inlet"]])) +
  annotate("text", x = xlens, y = ylens, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlens-1, y = ylens, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlens-2, y = ylens, colour = "99FF33", label = "Tahsis inlet")




# Correlation analysis by moving average
cor.data.m<-df%>%select(SYS_NM,Year,m.ave)%>%pivot_wider(names_from="Year",values_from="m.ave")%>%data.frame()

rownames(cor.data.m)<-cor.data.m$SYS_NM

cor.data.m<-cor.data.m%>%select(-SYS_NM)

cor.m<-cor(t(cor.data.m),use="pairwise.complete.obs")

# Dendrogram, factored by inlet, by moving average

dist.cor.m<- dist(cor.m)
clust.dist.cor.m <- hclust(dist.cor.m)

dendclust.m <- dendro_data(clust.dist.cor.m)
mlabs <- as.data.frame(dendclust.m[["labels"]][["label"]])
mlabs$order <- 1:length(mlabs[,1])
colnames(mlabs) <- c("SYS_NM", "order")
mlabs <- merge(streaminlet, mlabs, by = "SYS_NM")
mlabs <- mlabs %>%
  arrange(order)
inletlist <- as.factor(mlabs$inlet)
  
dendclust.m[["labels"]][["inlet"]] <- inletlist

xlenm <- .95 * length(mlabs$SYS_NM)
ylenm <- .95 * (max(dendclust.m[["segments"]][["y"]]))

ggdendrogram(dendclust.m, rotate = TRUE) +
  labs(title = "Moving average") +
  theme(axis.text.y = element_text(colour = dendclust.m[["labels"]][["inlet"]])) +
  annotate("text", x = xlenm, y = ylenm, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlenm-1, y = ylenm, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlenm-2, y = ylenm, colour = "99FF33", label = "Tahsis inlet")


# Corplots to knit
par(oma=c(2,2,2,2))
par(mfrow=c(2,2))
corrplot(cor.z, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5)
corrplot(cor.e, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5)
corrplot(cor.s, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5)
corrplot(cor.m, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5)



```


```{r correlations for side by side pre post,echo=FALSE,warning=FALSE,message=FALSE}
#prep data for correlations

cor.data.z<-df%>%select(SYS_NM,Year,z)%>%
  pivot_wider(names_from="Year",values_from="z")%>%data.frame()

cor.data.z.pre<-cor.data.z[,1:31]
rownames(cor.data.z.pre)<-cor.data.z.pre$SYS_NM
cor.data.z.pre<-cor.data.z.pre%>%select(-SYS_NM)
cor.z.pre<-cor(t(cor.data.z.pre),use="pairwise.complete.obs")

cor.data.z.post<-cor.data.z[,c(1,32:70)]
rownames(cor.data.z.post)<-cor.data.z.post$SYS_NM
cor.data.z.post<-cor.data.z.post%>%select(-SYS_NM)
cor.z.post<-cor(t(cor.data.z.post),use="pairwise.complete.obs")


par(mfrow=c(1,2))
corrplot(cor.z.pre, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Z-scores (Pre 1980)", mar=c(0,0,1,0))
corrplot(cor.z.post, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Z-score (Post 1980)", sub = "Z-scores", mar=c(0,0,1,0))

# Dendrogram, factored by inlet, by z-score

# Pre-1980
dist.cor.z.pre<- dist(cor.z.pre)
clust.dist.cor.z.pre <- hclust(dist.cor.z.pre)

dendclust.z.pre <- dendro_data(clust.dist.cor.z.pre)
zlabs.pre <- as.data.frame(dendclust.z.pre[["labels"]][["label"]])
zlabs.pre$order <- 1:length(zlabs.pre[,1])
colnames(zlabs.pre) <- c("SYS_NM", "order")
zlabs.pre <- merge(streaminlet, zlabs.pre, by = "SYS_NM")
zlabs.pre <- zlabs.pre %>%
  arrange(order)
inletlist.pre <- as.factor(zlabs.pre$inlet)
  
dendclust.z.pre[["labels"]][["inlet"]] <- inletlist.pre

xlenz.pre <- .95 * length(zlabs.pre$SYS_NM)
ylenz.pre <- .95 * (max(dendclust.z.pre[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.z.pre, rotate = TRUE) +
  labs(title = "Z-scores (Pre 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.z.pre[["labels"]][["inlet"]])) +
  annotate("text", x = xlenz.pre, y = ylenz.pre, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlenz.pre-1, y = ylenz.pre, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlenz.pre-2, y = ylenz.pre, colour = "99FF33", label = "Tahsis inlet") 

# Post-1980
dist.cor.z.post<- dist(cor.z.post)
clust.dist.cor.z.post <- hclust(dist.cor.z.post)

dendclust.z.post <- dendro_data(clust.dist.cor.z.post)
zlabs.post <- as.data.frame(dendclust.z.post[["labels"]][["label"]])
zlabs.post$order <- 1:length(zlabs.post[,1])
colnames(zlabs.post) <- c("SYS_NM", "order")
zlabs.post <- merge(streaminlet, zlabs.post, by = "SYS_NM")
zlabs.post <- zlabs.post %>%
  arrange(order)
inletlist.post <- as.factor(zlabs.post$inlet)
  
dendclust.z.post[["labels"]][["inlet"]] <- inletlist.post

xlenz.post <- .95 * length(zlabs.post$SYS_NM)
ylenz.post <- .95 * (max(dendclust.z.post[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.z.post, rotate = TRUE) +
  labs(title = "Z-scores (Post 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.z.post[["labels"]][["inlet"]])) +
  annotate("text", x = xlenz.post, y = ylenz.post, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlenz.post-1, y = ylenz.post, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlenz.post-2, y = ylenz.post, colour = "99FF33", label = "Tahsis inlet")



#insert cor pre-post analysis for each other metric
#esc.log
cor.data.e<-df%>%select(SYS_NM,Year,esc.log)%>%
  pivot_wider(names_from="Year",values_from="esc.log")%>%data.frame()

cor.data.e.pre<-cor.data.e[,1:31]
rownames(cor.data.e.pre)<-cor.data.e.pre$SYS_NM
cor.data.e.pre<-cor.data.e.pre%>%select(-SYS_NM)
cor.e.pre<-cor(t(cor.data.e.pre),use="pairwise.complete.obs")

cor.data.e.post<-cor.data.e[,c(1,32:70)]
rownames(cor.data.e.post)<-cor.data.e.post$SYS_NM
cor.data.e.post<-cor.data.e.post%>%select(-SYS_NM)
cor.e.post<-cor(t(cor.data.e.post),use="pairwise.complete.obs")

par(mfrow=c(1,2))
corrplot(cor.e.pre, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Log escapement (Pre 1980)", mar=c(0,0,1,0))
corrplot(cor.e.post, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Log escapement (Post 1980)", mar=c(0,0,1,0))

# Dendrogram, factored by inlet, by log escapement

# Pre-1980
dist.cor.e.pre<- dist(cor.e.pre)
clust.dist.cor.e.pre <- hclust(dist.cor.e.pre)

dendclust.e.pre <- dendro_data(clust.dist.cor.e.pre)
elabs.pre <- as.data.frame(dendclust.e.pre[["labels"]][["label"]])
elabs.pre$order <- 1:length(elabs.pre[,1])
colnames(elabs.pre) <- c("SYS_NM", "order")
elabs.pre <- merge(streaminlet, elabs.pre, by = "SYS_NM")
elabs.pre <- elabs.pre %>%
  arrange(order)
inletlist.pre <- as.factor(elabs.pre$inlet)
  
dendclust.e.pre[["labels"]][["inlet"]] <- inletlist.pre

xlene.pre <- .95 * length(elabs.pre$SYS_NM)
ylene.pre <- .95 * (max(dendclust.e.pre[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.e.pre, rotate = TRUE) +
  labs(title = "Log escapement (Pre 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.e.pre[["labels"]][["inlet"]])) +
  annotate("text", x = xlene.pre, y = ylene.pre, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlene.pre-1, y = ylene.pre, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlene.pre-2, y = ylene.pre, colour = "99FF33", label = "Tahsis inlet")

# Post-1980
dist.cor.e.post<- dist(cor.e.post)
clust.dist.cor.e.post <- hclust(dist.cor.e.post)

dendclust.e.post <- dendro_data(clust.dist.cor.e.post)
elabs.post <- as.data.frame(dendclust.e.post[["labels"]][["label"]])
elabs.post$order <- 1:length(elabs.post[,1])
colnames(elabs.post) <- c("SYS_NM", "order")
elabs.post <- merge(streaminlet, elabs.post, by = "SYS_NM")
elabs.post <- elabs.post %>%
  arrange(order)
inletlist.post <- as.factor(elabs.post$inlet)
  
dendclust.e.post[["labels"]][["inlet"]] <- inletlist.post

xlene.post <- .95 * length(elabs.post$SYS_NM)
ylene.post <- .95 * (max(dendclust.e.post[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.e.post, rotate = TRUE) +
  labs(title = "Log escapement (Post 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.e.post[["labels"]][["inlet"]])) +
  annotate("text", x = xlene.post, y = ylene.post, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlene.post-1, y = ylene.post, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlene.post-2, y = ylene.post, colour = "99FF33", label = "Tahsis inlet")


#esc.stand

cor.data.s<-df%>%select(SYS_NM,Year,esc.stand)%>%
  pivot_wider(names_from="Year",values_from="esc.stand")%>%data.frame()

cor.data.s.pre<-cor.data.s[,1:31]
rownames(cor.data.s.pre)<-cor.data.s.pre$SYS_NM
cor.data.s.pre<-cor.data.s.pre%>%select(-SYS_NM)
cor.s.pre<-cor(t(cor.data.s.pre),use="pairwise.complete.obs")

cor.data.s.post<-cor.data.s[,c(1,32:70)]
rownames(cor.data.s.post)<-cor.data.s.post$SYS_NM
cor.data.s.post<-cor.data.s.post%>%select(-SYS_NM)
cor.s.post<-cor(t(cor.data.s.post),use="pairwise.complete.obs")

par(mfrow=c(1,2))
corrplot(cor.s.pre, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Standardized escapement (Pre 1980)", mar=c(0,0,1,0))
corrplot(cor.s.post, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Standardized escapement (Post 1980)", mar=c(0,0,1,0))

# Dendrogram, factored by inlet, by standardized escapement

# Pre-1980
dist.cor.s.pre<- dist(cor.s.pre)
clust.dist.cor.s.pre <- hclust(dist.cor.s.pre)

dendclust.s.pre <- dendro_data(clust.dist.cor.s.pre)
slabs.pre <- as.data.frame(dendclust.s.pre[["labels"]][["label"]])
slabs.pre$order <- 1:length(slabs.pre[,1])
colnames(slabs.pre) <- c("SYS_NM", "order")
slabs.pre <- merge(streaminlet, slabs.pre, by = "SYS_NM")
slabs.pre <- slabs.pre %>%
  arrange(order)
inletlist.pre <- as.factor(slabs.pre$inlet)
  
dendclust.s.pre[["labels"]][["inlet"]] <- inletlist.pre

xlens.pre <- .95 * length(slabs.pre$SYS_NM)
ylens.pre <- .95 * (max(dendclust.s.pre[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.s.pre, rotate = TRUE) +
  labs(title = "Standardized escapement (Pre 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.s.pre[["labels"]][["inlet"]])) +
  annotate("text", x = xlens.pre, y = ylens.pre, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlens.pre-1, y = ylens.pre, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlens.pre-2, y = ylens.pre, colour = "99FF33", label = "Tahsis inlet") 

# Post-1980
dist.cor.s.post<- dist(cor.s.post)
clust.dist.cor.s.post <- hclust(dist.cor.s.post)

dendclust.s.post <- dendro_data(clust.dist.cor.s.post)
slabs.post <- as.data.frame(dendclust.s.post[["labels"]][["label"]])
slabs.post$order <- 1:length(slabs.post[,1])
colnames(slabs.post) <- c("SYS_NM", "order")
slabs.post <- merge(streaminlet, slabs.post, by = "SYS_NM")
slabs.post <- slabs.post %>%
  arrange(order)
inletlist.post <- as.factor(slabs.post$inlet)
  
dendclust.s.post[["labels"]][["inlet"]] <- inletlist.post

xlens.post <- .95 * length(slabs.post$SYS_NM)
ylens.post <- .95 * (max(dendclust.s.post[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.s.post, rotate = TRUE) +
  labs(title = "Standardized escapement (Post 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.s.post[["labels"]][["inlet"]])) +
  annotate("text", x = xlens.post, y = ylens.post, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlens.post-1, y = ylens.post, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlens.post-2, y = ylens.post, colour = "99FF33", label = "Tahsis inlet")


#m.ave

cor.data.m<-df%>%select(SYS_NM,Year,m.ave)%>%
  pivot_wider(names_from="Year",values_from="m.ave")%>%data.frame()

cor.data.m.pre<-cor.data.m[,1:31]
rownames(cor.data.m.pre)<-cor.data.m.pre$SYS_NM
cor.data.m.pre<-cor.data.m.pre%>%select(-SYS_NM)
cor.m.pre<-cor(t(cor.data.m.pre),use="pairwise.complete.obs")

cor.data.m.post<-cor.data.m[,c(1,32:70)]
rownames(cor.data.m.post)<-cor.data.m.post$SYS_NM
cor.data.m.post<-cor.data.m.post%>%select(-SYS_NM)
cor.m.post<-cor(t(cor.data.m.post),use="pairwise.complete.obs")

par(mfrow=c(1,2))
corrplot(cor.m.pre, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Moving average (Pre 1980)", mar=c(0,0,1,0))
corrplot(cor.m.post, diag = FALSE, order="hclust", method="square", tl.col="black",
         addrect = 6, tl.cex = 0.5, title = "Moving average (Post 1980)", mar=c(0,0,1,0))

# Dendrogram, factored by inlet, by m-score

# Pre-1980
dist.cor.m.pre<- dist(cor.m.pre)
clust.dist.cor.m.pre <- hclust(dist.cor.m.pre)

dendclust.m.pre <- dendro_data(clust.dist.cor.m.pre)
mlabs.pre <- as.data.frame(dendclust.m.pre[["labels"]][["label"]])
mlabs.pre$order <- 1:length(mlabs.pre[,1])
colnames(mlabs.pre) <- c("SYS_NM", "order")
mlabs.pre <- merge(streaminlet, mlabs.pre, by = "SYS_NM")
mlabs.pre <- mlabs.pre %>%
  arrange(order)
inletlist.pre <- as.factor(mlabs.pre$inlet)
  
dendclust.m.pre[["labels"]][["inlet"]] <- inletlist.pre

xlenm.pre <- .95 * length(mlabs.pre$SYS_NM)
ylenm.pre <- .95 * (max(dendclust.m.pre[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.m.pre, rotate = TRUE) +
  labs(title = "Moving average (Pre 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.m.pre[["labels"]][["inlet"]])) +
  annotate("text", x = xlenm.pre, y = ylenm.pre, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlenm.pre-1, y = ylenm.pre, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlenm.pre-2, y = ylenm.pre, colour = "99FF33", label = "Tahsis inlet") 

# Post-1980
dist.cor.m.post<- dist(cor.m.post)
clust.dist.cor.m.post <- hclust(dist.cor.m.post)

dendclust.m.post <- dendro_data(clust.dist.cor.m.post)
mlabs.post <- as.data.frame(dendclust.m.post[["labels"]][["label"]])
mlabs.post$order <- 1:length(mlabs.post[,1])
colnames(mlabs.post) <- c("SYS_NM", "order")
mlabs.post <- merge(streaminlet, mlabs.post, by = "SYS_NM")
mlabs.post <- mlabs.post %>%
  arrange(order)
inletlist.post <- as.factor(mlabs.post$inlet)
  
dendclust.m.post[["labels"]][["inlet"]] <- inletlist.post

xlenm.post <- .95 * length(mlabs.post$SYS_NM)
ylenm.post <- .95 * (max(dendclust.m.post[["segments"]][["y"]]))

par(mfrow=c(1,1))

ggdendrogram(dendclust.m.post, rotate = TRUE) +
  labs(title = "Moving average (Post 1980)") +
  theme(axis.text.y = element_text(colour = dendclust.m.post[["labels"]][["inlet"]])) +
  annotate("text", x = xlenm.post, y = ylenm.post, colour = "red", label = "Nootka inlet") +
  annotate("text", x = xlenm.post-1, y = ylenm.post, colour = "black", label = "Esperanza inlet") +  
  annotate("text", x = xlenm.post-2, y = ylenm.post, colour = "99FF33", label = "Tahsis inlet")


```

\newpage

```{r escapement bubble plot, fig.align="center",fig.height=8,fig.width=6,fig.cap="Escapement to area streams by enhancement rank.",echo=FALSE,warning=FALSE,message=FALSE}

par(mfrow = c(1, 1))
#bubbleplot of escapements for whole area
ggplot(df,aes(x=Year,y=SYS_NM,color=Enhancement_Rank,size=escapement))+
  geom_point(alpha=.5)+
  scale_colour_manual(breaks=c("NONE","LOW","HIGH"),
                      values=c("grey50","steelblue","darkred"))+
  labs(y="Escapement",color="Enhancement",x="Year",size="Escapement")+
  theme_bw()+
  theme(legend.position="bottom")
```

\newpage

```{r metric plots,fig.align="center",fig.height=8,fig.width=6,fig.cap="Various plots for escapement and transformations.",echo=FALSE,warning=FALSE,message=FALSE}
#plot streams by enhancement

p1<-ggplot(df,aes(x=Year,y=escapement,color=Enhancement_Rank,group=SYS_NM))+
  geom_line()+
  theme_bw()+
  labs(y="Escapement",title="Raw Escapement")

p2<-ggplot(df,aes(x=Year,y=esc.log,color=Enhancement_Rank,group=SYS_NM))+
 geom_line()+
  theme_bw()+
  labs(y="log(Escapement)",title="Logged Escapement")

p3<-ggplot(df,aes(x=Year,y=z,color=Enhancement_Rank,group=SYS_NM))+
  geom_line()+
  geom_hline(yintercept=0)+
  theme_bw()+
  labs(y="Z-scores (Escapement)",title="Z-scores Escapement")

p4<-ggplot(df,aes(x=Year,y=esc.stand,color=Enhancement_Rank,group=SYS_NM))+
  geom_line()+
  theme_bw()+
  labs(y="Standardized Escapement (pavg)",title="Escapement/Average (Pavg)")

ggarrange(p1,p2,p3,p4,ncol=1,common.legend = TRUE)

```

\newpage

```{r moving average and LOESS plots, echo=FALSE,warning=FALSE,message=FALSE,fig.align="center",fig.height=5,fig.width=6,fig.cap="Moving average and LOESS fits on logged escapement by enhancement ranking."}
t1<-ggplot(df,aes(x=Year,y=m.ave,color=Enhancement_Rank,group=SYS_NM))+
  geom_line()+
  theme_bw()+
  labs(y="Moving Average",title="Moving-Average")

t2<-ggplot(df,aes(x=Year,y=z,color=Enhancement_Rank,group=SYS_NM))+
  geom_smooth(method="loess",se=FALSE,span=.1,size=.7)+
  geom_hline(yintercept=0)+
  theme_bw()+
  labs(y="Z-score",title="Loess fit on Z-scores")

ggarrange(t1,t2,ncol=1,common.legend = TRUE)

```

\newpage

```{r prepost boxplot,echo=FALSE,warning=FALSE,message=FALSE,fig.align="center",fig.height=7,fig.width=6,fig.cap="Z-scores pre- and post-enhancement."}
ggplot(df,aes(y=SYS_NM,x=z,fill=prepost))+
  geom_boxplot()+
  geom_vline(xintercept=0)+
  theme_bw()+
  labs(y="System Name",x="Z-score")
```

\newpage

```{r correlation plots, echo=FALSE,warning=FALSE,message=FALSE,fig.align="center",fig.height=7,fig.width=6,fig.cap="Cross correlation plots to compare metrics."}

#png("~/R/PSF Hatchery Review/analysis/spatial/outputs/corrplots.png",res=600,units="in",height=9,width=7)
par(oma=c(2,2,2,2))
par(mfrow=c(2,2))
corrplot(cor.z,diag=FALSE,order="hclust",addrect=6,method="square",tl.col="black",tl.cex=.5)
corrplot(cor.z,diag=FALSE,order="hclust",addrect=6,method="square",tl.col="black",tl.cex=.5)
corrplot(cor.z,diag=FALSE,order="hclust",addrect=6,method="square",tl.col="black",tl.cex=.5)
corrplot(cor.z,diag=FALSE,order="hclust",addrect=6,method="square",tl.col="black",tl.cex=.5)

#dev.off()

#ggarrange(c1,c2,common.legend = TRUE,ncol=1)


```

```{r correlation plots pre post, echo=FALSE,warning=FALSE,message=FALSE,fig.align="center",fig.height=8,fig.width=6,fig.cap="Cross correlation plots to compare pre- and post-enhancement."}

#png("~/R/PSF Hatchery Review/analysis/spatial/outputs/corrplots.png",res=600,units="in",height=9,width=7)

par(mar=c(1,5,8,1))
par(oma=c(1,1,1,1))
par(mfrow=c(2,1))
corrplot(cor.z.pre,diag=FALSE,order="hclust",addrect=6,method="square",mar=c(1,2,3,1),
         tl.col="black",tl.cex=.3,title="Pre-Enhancement (1980)")
corrplot(cor.z.post,diag=FALSE,order="hclust",addrect=6,method="square",mar=c(1,2,3,1),
         tl.col="black",tl.cex=.3,title="Post-Enhancement (1980)")

#dev.off()

#ggarrange(c1,c2,common.legend = TRUE,ncol=1)


```



```{r, include=FALSE,eval=FALSE}

rel<-fread("~/R/PSF hatchery review/releases/AllSEPReleases_2020-04-21_Original.csv")

names(rel)
str(rel)

allreleases<-rel%>%select(SPECIES_NAME,STOCK_NAME,FACILITY_NAME,RELEASE_SITE_NAME,RELEASE_STAGE_NAME,TotalRelease,RELEASE_YEAR)%>%
  group_by(SPECIES_NAME,STOCK_NAME,RELEASE_SITE_NAME,FACILITY_NAME,RELEASE_STAGE_NAME,RELEASE_YEAR)%>%
  summarise(releases=sum(as.numeric(TotalRelease)),n=n())

cd<-allreleases%>%filter(SPECIES_NAME=="Chum")

getall<-unique(c(grep("Conuma",cd$RELEASE_SITE_NAME),
          grep("Conuma",cd$STOCK_NAME),
          grep("Canton",cd$RELEASE_SITE_NAME),
          grep("Canton",cd$STOCK_NAME),
          grep("Sucwoa",cd$RELEASE_SITE_NAME),
          grep("Sucwoa",cd$STOCK_NAME),
          grep("Tlupana",cd$RELEASE_SITE_NAME),
          grep("Tlupana",cd$STOCK_NAME),
          grep("Zeballos",cd$RELEASE_SITE_NAME),
          grep("Zeballos",cd$STOCK_NAME)))
          
a26.rel.prep<-cd[getall,]

ggplot(a26.rel.prep,aes(x=RELEASE_YEAR,y=releases,color=RELEASE_STAGE_NAME))+
  geom_point()+geom_line()+
  facet_grid(RELEASE_SITE_NAME~STOCK_NAME)+
  theme_bw()+
  theme(legend.position = "bottom")

ggplot(a26.rel.prep,aes(x=RELEASE_YEAR,y=releases,color=RELEASE_STAGE_NAME,shape=STOCK_NAME))+
  geom_point()+geom_line()+
  facet_wrap(~RELEASE_SITE_NAME,scale="free_y",ncol=1)+
  theme_bw()+
  theme(legend.position = "bottom")
```


```{r,include=FALSE,eval=FALSE}
cd%>%filter(RELEASE_SITE_NAME)

atup<-cd%>%filter(RELEASE_SITE_NAME=="Atnarko R Up"&SPECIES_NAME=="Chinook")
atlow<-cd%>%filter(RELEASE_SITE_NAME=="Atnarko R Low"&SPECIES_NAME=="Chinook")
#nimp<-cd%>%filter(RELEASE_SITE_NAME=="Nimpkish R"&SPECIES_NAME=="Chinook")
kitimat<-cd%>%filter(RELEASE_SITE_NAME=="Kitimat R"&SPECIES_NAME=="Chinook")

nimpCN<-cd%>%filter(RELEASE_SITE_NAME=="Nimpkish R"&SPECIES_NAME=="Chinook")
nimpall<-cd%>%filter(RELEASE_SITE_NAME=="Nimpkish R")
atn<-rbind(atup,atlow)

ggdata<-kitimat

idx <- c(1, diff(ggdata$RELEASE_YEAR))
i2 <- c(1,which(idx != 1), nrow(ggdata)+1)
#adds a grouping column for ggplot to use
ggdata$grp <- rep(1:length(diff(i2)), diff(i2))


ggplot(ggdata,aes(x=RELEASE_YEAR,y=releases,color=RELEASE_STAGE_NAME,shape=RELEASE_SITE_NAME,group=grp))+
  geom_line()+
  geom_point()+
  #facet_wrap(~STOCK_NAME+SPECIES_NAME,ncol=2,scales="free_y")+
  facet_wrap(~STOCK_NAME,ncol=1,scales="free_y")+
  #facet_grid(STOCK_NAME~SPECIES_NAME,scales="free_y")+
  labs(y="Releases",x="Release Year",color="Release Stage",shape="Release Site Name")+
  theme_bw()+
  theme(legend.position="bottom",legend.box = "vertical")

ggsave("Nimpkish CN only releases facet grid.png",dpi=600,height=10,width=8)
```

```{r old code,include=FALSE,eval=FALSE}
#included systems
dfwide<-df%>%select(SYS_NM,Enhancement_Rank,Year,escapement)%>%
  pivot_wider(names_from="Year",values_from="escapement")

#count number of observations in last 10 years
dfwide$n10<-apply(dfwide[,3:70],1,function(x) x=sum(!is.na(x[61:71])))

#run a filter to exclude any stream with less than 3 counts in last 10 years
esc.incl1<-subset(dfwide,n10>3)

##standardized escapements
esc.s<-esc.incl1

esc.s$u.esc<-apply(esc.s[3:71],1,function(x) mean(x,na.rm=TRUE))

esc.s[3:71]<-esc.s[3:71]/esc.s$u.esc

#setup for cross correlation
esc.cm<-esc.s%>%select(-n10,-u.esc,-Enhancement_Rank)%>%data.frame()

rownames(esc.cm)<-esc.cm$SYS_NM

cm<-cor(t(esc.cm[,-1]),use="complete.obs")

corrplot(cm,type="upper",order="hclust",method="square",tl.col="black")

#logged escapements
names(esc.incl1)

esc.log<-esc.incl1
esc.log[,3:71] <-log(esc.log[3:71],2)

esc.log2<-esc.log%>%select(-n10,-Enhancement_Rank)%>%data.frame()

rownames(esc.log2)<-esc.log2$SYS_NM


df%>%group_by(SYS_NM)%>%filter(Year>2008)%>%summarise(x=sum(!is.na(escapement)))

```

